### ISSUE TITLE
replaceMuCommaLambda in multi-objective case leads to subscript out of bounds error

### ISSUE THREAD

**Issue by susanne-207** [jakobbossek/ecr2#122]
When `survival.strategy = "comma"` in `ecr` for the multi-objective case, an error "subscript out of bounds" due to `as.numeric(fitness)` in `replaceMuCommaLambda` is triggered: 

```
fn = function(x) {
  y1 = sum(x^2)
  y2 = sqrt(sum(x^2))
  c(y1, y2)
}
lower = c(-5, -5); upper = c(5, 5)
set.seed(1234)
res = ecr(fn, n.dim = 2L, n.objectives = 2L, lower = lower, upper = lower,
  representation = "float", mu = 20L, lambda = 20L, survival.strategy = "comma",
  n.elite = 10L,
  mutator = setup(mutGauss, lower = lower, upper = upper), 
  recombinator = setup(recSBX, lower = lower, upper = upper))
```

**Comment by jakobbossek** [comment]
Hi,

Elitism (via parameter `n.elite`) in its current implementation does not make sense in the case of >= 2 objectives. This is because the elitism procedure sorts individuals with respect to their fitness. In the multi-objective setting there are usually solutions which are incomparable and therefore no total order can be established. Note that for some values of `n.elite`, your code runs fine, but the results may be corrupt.

In fact we have a FIXME in the code which says to catch what you tried and raise an error 🙈😅 However, so far this catching is not implemented.

Best,
Jakob
