### ISSUE TITLE
Suggestion: Population as parameter of `selectForSurvival` and `selNondom`

### ISSUE THREAD

**Issue by susanne-207** [jakobbossek/ecr2#123]
In my application case, solutions should not only be diverse on the objective space, but also the decision space. Thus, I have written my own version of `computeCrowdingDistance()` with input parameters fitness matrix and the list of candidates, which have those fitness values.  
However, `selectForSurvival()` and `selNondom ()` do not owe an argument to pass the population. Is there a way to make all those functions more flexible, so I do not have to rewrite them all?  
Another option would be to add the population to fitness as an attribute.

**Comment by jakobbossek** [comment]
No at the moment there is no possibility to pass further arguments down to selectors "dynamically", i.e., within the evolutionary loop inside the `ecr(...)` function. This is done to keep the interface uncluttered.

However, since ecr is a white-box framework you can write the evolutionary loop by hand and call functions as you like. I.e., do not use selectForSurvival, but instead call you own selector directly. This way you can pass whatever you like.

**Comment by jakobbossek** [comment]
Guess we are done here.
